// DESCRIPTION: Generated by verilator_includer via makefile
#define VL_INCLUDE_OPT include
#include "Vauriga_harness.cpp"
#include "Vauriga_harness__Trace.cpp"
#include "Vauriga_harness__Slow.cpp"
#include "Vauriga_harness__Syms.cpp"
#include "Vauriga_harness__Trace__Slow.cpp"
